"""
Rules package for PyAirflowTester.

Contains rule definitions for DAG, dbt, configuration, and other analysis.
"""

from pyairflowtester.rules.config import (
    AirflowCfgPoolConfigurationRule,
    ConcurrencyConfigurationRule,
    DAGFolderConfigurationRule,
    DatabaseBackupRule,
    EncryptionConfigurationRule,
    ExecutorConfigurationRule,
    LogRetentionRule,
    LogStorageRule,
    MaxActiveRunsRule,
    QueueConfigurationRule,
    RBACConfigurationRule,
    SchedulerConfigurationRule,
    TLSConfigurationRule,
    WorkerConfigurationRule,
    XComConfigurationRule,
)
from pyairflowtester.rules.dag import (
    CircularDependencyRule,
    ExpensiveImportsRule,
    MissingSLARule,
    ParseTimeRule,
)
from pyairflowtester.rules.dag_advanced import (
    AlertingConfigurationRule,
    BranchComplexityRule,
    CatchupConfigRule,
    DocumentationRule,
    HardcodedConnectionRule,
    OperatorDeprecationRule,
    RetryConfigurationRule,
    SecretsInCodeRule,
    SensorTimeoutRule,
    SourceCodePoolConfigurationRule,
    TaskCountRule,
)
from pyairflowtester.rules.dbt import (
    MissingTestsRule,
    RedundantTestsRule,
    UntestedModelRule,
)


def get_all_rules():
    """Get all available rules (35 total)."""
    return [
        # DAG Analysis Rules (AFW001-AFW015)
        {
            "id": "AFW001",
            "name": "Circular Dependency",
            "severity": "critical",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Detect circular task dependencies",
        },
        {
            "id": "AFW002",
            "name": "Missing SLA",
            "severity": "high",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Detect missing SLA on production DAG",
        },
        {
            "id": "AFW003",
            "name": "Expensive Imports",
            "severity": "medium",
            "category": "performance",
            "execution_mode": "static",
            "description": "Detect expensive imports in DAG file",
        },
        {
            "id": "AFW004",
            "name": "Parse Time",
            "severity": "medium",
            "category": "performance",
            "execution_mode": "static",
            "description": "Analyze DAG parse time",
        },
        {
            "id": "AFW005",
            "name": "Excessive Task Count",
            "severity": "medium",
            "category": "performance",
            "execution_mode": "static",
            "description": "Detect DAGs with > 500 tasks",
        },
        {
            "id": "AFW006",
            "name": "Risky Catchup Configuration",
            "severity": "high",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Detect catchup=True without backfill strategy",
        },
        {
            "id": "AFW007",
            "name": "Default Pool Usage",
            "severity": "medium",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Detect tasks using default pool",
        },
        {
            "id": "AFW008",
            "name": "Hardcoded Connection ID",
            "severity": "high",
            "category": "maintainability",
            "execution_mode": "static",
            "description": "Detect hardcoded connection strings",
        },
        {
            "id": "AFW009",
            "name": "Secrets in Code",
            "severity": "critical",
            "category": "security",
            "execution_mode": "static",
            "description": "Detect hardcoded secrets",
        },
        {
            "id": "AFW010",
            "name": "Excessive Retries",
            "severity": "medium",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Detect retries > 5 without backoff",
        },
        {
            "id": "AFW011",
            "name": "Sensor Timeout Risk",
            "severity": "medium",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Detect sensors with > 1h timeout",
        },
        {
            "id": "AFW012",
            "name": "Complex Branching",
            "severity": "low",
            "category": "maintainability",
            "execution_mode": "static",
            "description": "Detect complex BranchPythonOperator logic",
        },
        {
            "id": "AFW013",
            "name": "Missing Documentation",
            "severity": "low",
            "category": "maintainability",
            "execution_mode": "static",
            "description": "Detect DAGs without description",
        },
        {
            "id": "AFW014",
            "name": "No Alerting Configured",
            "severity": "medium",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Detect production DAGs without alerts",
        },
        {
            "id": "AFW015",
            "name": "Deprecated Operator",
            "severity": "medium",
            "category": "maintainability",
            "execution_mode": "static",
            "description": "Detect deprecated Airflow operators",
        },
        # dbt Analysis Rules (DBT001-DBT003)
        {
            "id": "DBT001",
            "name": "Missing Tests",
            "severity": "high",
            "category": "data_quality",
            "execution_mode": "static",
            "description": "Detect models without tests",
        },
        {
            "id": "DBT002",
            "name": "Redundant Tests",
            "severity": "low",
            "category": "maintainability",
            "execution_mode": "static",
            "description": "Detect redundant test definitions",
        },
        {
            "id": "DBT003",
            "name": "Untested Model",
            "severity": "medium",
            "category": "data_quality",
            "execution_mode": "static",
            "description": "Detect untested public models",
        },
        # Configuration Audit Rules (CFG001-CFG015)
        {
            "id": "CFG001",
            "name": "Executor Misconfiguration",
            "severity": "high",
            "category": "performance",
            "execution_mode": "static",
            "description": "Check executor type matches workload",
        },
        {
            "id": "CFG002",
            "name": "Pool Size Mismatch",
            "severity": "medium",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Check pool sizes adequate",
        },
        {
            "id": "CFG003",
            "name": "Concurrency Mismatch",
            "severity": "medium",
            "category": "performance",
            "execution_mode": "static",
            "description": "Check DAG/task concurrency settings",
        },
        {
            "id": "CFG004",
            "name": "Queue Bottleneck",
            "severity": "medium",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Check queue configuration",
        },
        {
            "id": "CFG005",
            "name": "Max Active Runs Not Limited",
            "severity": "high",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Check max_active_dag_runs limit",
        },
        {
            "id": "CFG006",
            "name": "XCom Backend Issue",
            "severity": "medium",
            "category": "performance",
            "execution_mode": "static",
            "description": "Check XCom configuration",
        },
        {
            "id": "CFG007",
            "name": "Insufficient Log Retention",
            "severity": "medium",
            "category": "compliance",
            "execution_mode": "static",
            "description": "Check log retention >= 30 days",
        },
        {
            "id": "CFG008",
            "name": "Encryption Not Configured",
            "severity": "high",
            "category": "security",
            "execution_mode": "static",
            "description": "Check Fernet encryption configured",
        },
        {
            "id": "CFG009",
            "name": "TLS Not Enabled",
            "severity": "high",
            "category": "security",
            "execution_mode": "static",
            "description": "Check TLS for web UI",
        },
        {
            "id": "CFG010",
            "name": "RBAC Disabled",
            "severity": "high",
            "category": "security",
            "execution_mode": "static",
            "description": "Check RBAC enabled",
        },
        {
            "id": "CFG011",
            "name": "Scheduler Misconfiguration",
            "severity": "medium",
            "category": "performance",
            "execution_mode": "static",
            "description": "Check scheduler settings",
        },
        {
            "id": "CFG012",
            "name": "Worker Misconfiguration",
            "severity": "medium",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Check worker configuration",
        },
        {
            "id": "CFG013",
            "name": "Local Log Storage",
            "severity": "high",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Check log storage location",
        },
        {
            "id": "CFG014",
            "name": "No Database Backup",
            "severity": "high",
            "category": "reliability",
            "execution_mode": "static",
            "description": "Check database backup configuration",
        },
        {
            "id": "CFG015",
            "name": "DAG Folder On NFS",
            "severity": "medium",
            "category": "performance",
            "execution_mode": "static",
            "description": "Check DAG folder location",
        },
    ]


__all__ = [
    # DAG Rules
    "CircularDependencyRule",
    "MissingSLARule",
    "ExpensiveImportsRule",
    "ParseTimeRule",
    "TaskCountRule",
    "CatchupConfigRule",
    "SourceCodePoolConfigurationRule",
    "HardcodedConnectionRule",
    "SecretsInCodeRule",
    "RetryConfigurationRule",
    "SensorTimeoutRule",
    "BranchComplexityRule",
    "DocumentationRule",
    "AlertingConfigurationRule",
    "OperatorDeprecationRule",
    # dbt Rules
    "MissingTestsRule",
    "RedundantTestsRule",
    "UntestedModelRule",
    # Config Rules
    "ExecutorConfigurationRule",
    "AirflowCfgPoolConfigurationRule",
    "ConcurrencyConfigurationRule",
    "QueueConfigurationRule",
    "MaxActiveRunsRule",
    "XComConfigurationRule",
    "LogRetentionRule",
    "EncryptionConfigurationRule",
    "TLSConfigurationRule",
    "RBACConfigurationRule",
    "SchedulerConfigurationRule",
    "WorkerConfigurationRule",
    "LogStorageRule",
    "DatabaseBackupRule",
    "DAGFolderConfigurationRule",
    "get_all_rules",
]
